@startuml
[*] --> NotEnrolled: "Course browsing"
NotEnrolled --> Enrolling: "Selects course"
Enrolling --> Enrolled: "Enrollment successful"

Enrolled --> NotEnrolled: "Course completion"
Enrolled --> NotEnrolling: "Withdraws"

Enrolling --> NotEnrolled: "Enrollment failed"
@enduml
